# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "biopay"
merchant_id: "****____MERCHANT_ID____****"
merchant_hash_key: "****____MERCHANT_HASH_KEY____****"
email_from: 'Biodiesel Co-op <billing@vancouverbiodiesel.org>'
sysadmin_email: 'luke@vancouverbiodiesel.org'
board_email: 'vancouver-biodiesel-board@googlegroups.com'


# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

plugins:
  CouchDB:
    uri: "****____COUCH_URI____****"
  Auth::RBAC:
    credentials:
      class: CouchDB
    permissions:
      class: Config
      options:
        control:
          admin:
            permissions:
              manage accounts:
                operations: ["view"]

session: "cookie"
session_cookie_key: "****____DEV_KEY____****"
